dist: trusty

language: java

#jdk:
#  - oraclejdk8
jdk:
  - oraclejdk11
  
#script: mvn clean install
script:
  - javac PriorityQueueTest.java
  - java PriorityQueueTest
#  - ant test

#jobs:
#  include:
#    - stage: Custom Testing
#      #name: Pass
#      name: Fail
