language: java
#java:
#  - "1.8.0"
before_install:
  - echo "before_install"

install:
  - echo "install"
  - 
before_script:
  - echo "before_script"

script:
  - ./PriorityQueueTest.java 
  #- echo "script"

jobs:
  include:
    - stage: Custom Testing
#      name: Pass
      name: Fail
