language: java

jdk:
  - oraclejdk11

script:
 - javac -d . -classpath .:junit-4.12.jar PriorityQueueTest.java TestRunner.java
 - java -classpath .:junit-4.12.jar TestRunner
 

 #- javac -d . -classpath .:junit-4.12.jar PriorityQueueTest.java
 #- javac -classpath .:junit-4.12.jar TestRunner.java 
 #- java -classpath .:junit-4.12.jar TestRunner






# ---
#script: mvn clean install

#dist: trusty

#jdk:
#  - oraclejdk8

#addons:
#  apt:
#    packages:
#    - junit4
    
#before_install:
#  - travis_apt_get_update

#install:
#  - sudo apt-get install junit
#  - sudo apt-get install junit4
#  - sudo apt-get install junit5

# - javac -classpath junit-4.12.jar PriorityQueueTest.java TestRunner.java
# - java PriorityQueueTest.class
# - java -jar junit-4.12.jar
# - javac PriorityQueueTest.java
# javac -classpath ".:/home/path/mail.jar:/home/path/servlet.jar:" MyJavaFile.java
# javac -cp ".;first.jar;second.jar;third.jar" MyJavaFile.java

# javac -cp ".:./jars/common.jar" helloworld.java # For Windows, ":" should be replaced with ";".
#- javac -cp junit-4.12.jar PriorityQueueTest.java
#  - ant test

#jobs:
#  include:
#    - stage: Custom Testing
#      #name: Pass
#      name: Fail
