#dist: trusty

language: java

#jdk:
#  - oraclejdk8
jdk:
  - oraclejdk11

#addons:
#  apt:
#    packages:
#    - junit4
    
#before_install:
#  - travis_apt_get_update

#install:
#  - sudo apt-get install junit
#  - sudo apt-get install junit4
#  - sudo apt-get install junit5

#script: mvn clean install
script:
 - javac -d . -classpath .:junit-4.12.jar PriorityQueueTest.java TestRunner.java
 #- javac -d . -classpath junit-4.12.jar PriorityQueueTest.java
 #- javac PriorityQueueTest.java
 #- ls
 #- cd Lab4
 #- ls
 #- cd ..
 #- java Lab4.PriorityQueueTest
 #- javac -d . -cp junit-4.12.jar:Lab4.PriorityQueueTest.class TestRunner.java
 #- javac TestRunner.java
 #- ls
 - java .:junit-4.12.jar TestRunner
 #- ls
# - javac -classpath junit-4.12.jar PriorityQueueTest.java TestRunner.java
# - java PriorityQueueTest.class
# - java -jar junit-4.12.jar
# - javac PriorityQueueTest.java
# javac -classpath ".:/home/path/mail.jar:/home/path/servlet.jar:" MyJavaFile.java
# javac -cp ".;first.jar;second.jar;third.jar" MyJavaFile.java

# javac -cp ".:./jars/common.jar" helloworld.java # For Windows, ":" should be replaced with ";".
  #- javac -cp junit-4.12.jar PriorityQueueTest.java
  
#  - ant test

#jobs:
#  include:
#    - stage: Custom Testing
#      #name: Pass
#      name: Fail
