language: java

os:
- windows

#jdk:
#- oraclejdk11

before_install:
  - echo "before_install"

install:
  - echo "install"
  - 
before_script:
  - echo "before_script"

script:
  #- echo "script"

jobs:
  include:
    - stage: Custom Testing
#      name: Pass
      name: Fail
