language: java
jdk:
  - oraclejdk8
script: mvn clean install

#language: java

#jdk:
#  - oraclejdk11
  
#script: mvn clean install

#script:
#  - ant test
#  - javac PriorityQueueTest.java
#  java PriorityQueueTest.java
