#dist: trusty

language: java

#jdk:
#  - oraclejdk8
jdk:
  - oraclejdk11
  
#before_install:
#  - travis_apt_get_update

#install:
#  - sudo apt-get install junit
#  - sudo apt-get install junit4
#  - sudo apt-get install junit5

#script: mvn clean install
script:
#  - javac PriorityQueueTest.java
# javac -classpath ".:/home/path/mail.jar:/home/path/servlet.jar:" MyJavaFile.java
# javac -cp ".;first.jar;second.jar;third.jar" MyJavaFile.java
#  - javac -cp ".;junit-4.12.jar;" PriorityQueueTest.java
  - javac -classpath ".;junit-4.12.jar;" PriorityQueueTest.java
  - java PriorityQueueTest
#  - ant test

#jobs:
#  include:
#    - stage: Custom Testing
#      #name: Pass
#      name: Fail
